# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cef0d1165c8dd4b8b2524c28a56540b14d417dc17cb44060aca61674d5bfda879b727911c8dd3cc9a2907a3754d30b0d126c55831751bd82beee54e9e97b358

test:
  secret_key_base: b84b519d793300843bf95cbfff4aba87f03435e3790281c8bdf93130b61b7864450b9873ffef8975726d332a6481b62c87ddc3fb9ef7704375651aa4ba5027f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
